<a href="https://colab.research.google.com/github/GautamChy/Data-Science-Journey/blob/main/18_Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification ---> Supervised ML
* Classification means True or False , 0 or 1 yesto kura haru classify garney or category haru predict garney kura classification maa parchha.
# Output -> Categorical
* Output data categorical ma paryo vanney tyo nai classification ho.
# 2 Categories --> Yes/No
* 2 ota categories chha i.e Yes/No tyea madhea total
 dataset ko size 1000 rows  chha vanney 900 ota Yes and 100 ota No.
 # 1000 Datapoints in dataset
* dataset ko size 1000 rows  chha vanney
 # 900 Yes and 100 No
 * 900 ota Yes and 100 ota No.


 * 900 : 100 --> 9:1 [Imbalanced Dataset]
* 500 : 500 --> 1:1 [Balanced Dataset]
* 600 : 400 --> 6:4 [Balanced Dataset]  lagbhagh balanced chha.
* 700 : 300 --> [ Can be imbalanced or balanced according to condition]

# Tecchniques to handle imbalanced dataset
* Upsamping : It means ghataidinney
* Downsamping: It means ghataidiney

 # Upsampling:
   * Upsampling means increasing the number of samples in the minority class.
  
  Goal:
  * Make classes more balanced.

  Mothods:
  * Duplicate existing minority samples
* Generate synthetic data (like SMOTE)

Example:
*  Before:

* Fraud = 50
* No Fraud = 950

* After upsampling:

* Fraud = 950
* No Fraud = 950

Advantages:
* Keeps all original data
* Helps model learn minority patterns better

Disadvantages:
* Can cause overfitting if duplicates are repeated too much

# Downsampling
* Downsampling means reducing the number of samples in the majority class.

Example

* Before:

* Fraud = 50
* No Fraud = 950

After downsampling:

* Fraud = 50
* No Fraud = 50

Advantages:
* Faster training
* Reduces dominance of majority class

Disadvantages:
* Loses potentially useful information




# Simple analogy
* Imagine a classroom vote:

* 95 students prefer tea
* 5 prefer coffee

To make opinions balanced:

* Upsampling → ask the 5 coffee students to speak multiple times
* Downsampling → randomly choose only 5 tea students to participate



These methods are especially common in:

* Fraud detection
* Medical diagnosis
* Spam detection
* Rare event prediction

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
n_class_0 =  900  # 900 data store
n_class_1 = 100   # 100 data stire

In [ ]:
# making dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(0, 1, 900),
    'feature_2' : np.random.normal(0, 1, 900),
    'target' : [0]*900
})

In [ ]:
class_0

     feature_1  feature_2  target
0     0.418004  -0.661411       0
1     0.909296  -0.427340       0
2     0.124561   0.428596       0
3    -2.496944   2.199763       0
4    -0.456709   0.271034       0
..         ...        ...     ...
895   1.253145   0.720058       0
896   0.394931  -0.146939       0
897   0.568810  -1.385623       0
898   0.656932   0.269140       0
899   0.856557  -1.112635       0

[900 rows x 3 columns]

In [ ]:
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(2, 1, 100),
    'feature_2':np.random.normal(2, 1, 100),
    'target':[1]*100
})

In [ ]:
class_1

    feature_1  feature_2  target
0    2.566563   5.144345       1
1    3.085428   3.976537       1
2    1.510166  -0.349517       1
3    3.048564   1.148793       1
4    1.550408   1.582506       1
..        ...        ...     ...
95   3.422163   2.065734       1
96   0.835948   2.750451       1
97   1.910977   3.106827       1
98   1.634046   1.974297       1
99   1.577334   2.230961       1

[100 rows x 3 columns]

In [ ]:
class_0.shape, class_1.shape

((900, 3), (100, 3))

In [ ]:
# Combining two DataFrames
df = pd.concat([class_0, class_1])

In [ ]:
# Checking 05 rows from top
df.head()

   feature_1  feature_2  target
0   0.418004  -0.661411       0
1   0.909296  -0.427340       0
2   0.124561   0.428596       0
3  -2.496944   2.199763       0
4  -0.456709   0.271034       0

In [ ]:
# checking 05 rows from buttom
df.tail()

    feature_1  feature_2  target
95   3.422163   2.065734       1
96   0.835948   2.750451       1
97   1.910977   3.106827       1
98   1.634046   1.974297       1
99   1.577334   2.230961       1

In [ ]:
# reset_index(drop=True) => Resets the row index to a clean sequence: 0, 1, 2, ..., drop=True means:, Do not keep the old index as a column, Just discard it
# Without drop=True, you’d get an extra column called "index"
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [ ]:
df.head()

   feature_1  feature_2  target
0   0.418004  -0.661411       0
1   0.909296  -0.427340       0
2   0.124561   0.428596       0
3  -2.496944   2.199763       0
4  -0.456709   0.271034       0

In [ ]:
df.shape

(1000, 3)

In [ ]:
# Counts the frequency of each unique value of target column
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

# Upsamping
* Upsampling means increasing the number of samples in the minority class.

In [ ]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [ ]:
df_minority.shape, df_majority.shape

((100, 3), (900, 3))

In [ ]:
from sklearn.utils import resample
# replace=True → allows duplicates → required for upsampling
# n_samples=len(df_majority) → expands minority class to match majority size
# Upsampling → replace=True
df_minority_upsampled = resample(df_minority, replace=True, n_samples =  len(df_majority)) # resample vitra (df_minority, replace=True, n_samples =  len(df_majority)) haalney.
                                                                                          # replace = True means increase gardiney i.e Upsampling ma jailey replace = True hunxa.
                                                                                          # n_samples =  len(df_majority)) it means length increase gardiney.

In [ ]:
df_minority_upsampled

     feature_1  feature_2  target
960   2.551035   1.745804       1
937   2.596115   1.608468       1
966   2.099020   2.657634       1
940   1.216732   1.924608       1
963  -0.269957   4.056894       1
..         ...        ...     ...
931   3.180733   2.544080       1
937   2.596115   1.608468       1
910   1.684892   0.533172       1
941   1.369260   1.317649       1
918   3.008418   2.601742       1

[900 rows x 3 columns]

# Downsampling
* Downsampling means reducing the number of samples in the majority class.

In [ ]:
from sklearn.utils import resample
# replace=False means sampling without replacement
# n_samples=len(df_minority) is likely smaller than the majority class
# Downsampling → replace=False
df_majority_downsampling = resample(df_majority, replace=False, n_samples =  len(df_minority)) # replace = True means decrease gardiney i.e Upsampling ma jailey replace = False hunxa.

In [ ]:
df_majority_downsampling

     feature_1  feature_2  target
627  -0.713253   0.981236       0
602  -0.148113  -0.488676       0
7     2.451960  -0.344934       0
246  -1.363691  -0.928215       0
857  -0.916297   1.223187       0
..         ...        ...     ...
114   1.059426   2.333609       0
333   1.071250   0.064445       0
3    -2.496944   2.199763       0
135  -1.299666   0.833362       0
632   0.206771  -0.428594       0

[100 rows x 3 columns]