<a href="https://colab.research.google.com/github/GautamChy/Data-Science-Journey/blob/main/PandasDay01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s = pd.Series([10,20,30,40]) # left side ko columm ma  index and right side ko column ma  value hunxa.
print(s)                     # dtype means value haru ko data. i.e 64bit ko integer chha it means.

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s = pd.Series([10,20,30], index= ["a","b","c"]) # aafai ley index pani haalna milyo
print(s)

a    10
b    20
c    30
dtype: int64

In [ ]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
s.values

array([10, 20, 30])

In [ ]:
s['b']

np.int64(20)

In [ ]:
s['c']

np.int64(30)

# DataFrame
- dherai ota Data haru vayo vanney DataFrame vanna milxa.
- 2D is a DataFrame but not 1D
- NOTE: 1D vanney ko Series and 2D  vanney ko DataFrame
- NOTE: Dictionary ma key and value jastai garney BUT key represent garxa column DataFrame ma.

In [ ]:
df = pd.DataFrame({
    'name' : ['Ramesh', 'Rajesh', 'Rabin'],  # name is column, Ramesh,Rajesh,Rabin is value of the column
    'age'  : [25,30,40],
    'salary' : [30000, 400000,70000]
})

print(df)                          # 0,1,2, output is an index.

     name  age  salary
0  Ramesh   25   30000
1  Rajesh   30  400000
2   Rabin   40   70000

# CSV = It means comma seperated values
- df = pd.read_csv("file vitra ko data name")
  - df.head()

In [ ]:
df = pd.read_csv("google_stock_price.csv")
df.head()

         Date     Price
0  2004-08-19  2.490664
1  2004-08-20  2.515820
2  2004-08-23  2.758411
3  2004-08-24  2.770615
4  2004-08-25  2.614201

Excel file read garna lai.
- df = pd.read_excel

json file read garna lai
- df = pd.read_json

In [ ]:
df = pd.read_csv("pokemon.csv")
df.head()

         Name           Type
0   Bulbasaur  Grass, Poison
1     Ivysaur  Grass, Poison
2    Venusaur  Grass, Poison
3  Charmander           Fire
4  Charmeleon           Fire

In [ ]:
df = pd.read_csv("revenue.csv")
df.head()

     Date  New York  Los Angeles  Miami
0  1/1/26       985          122    499
1  1/2/26       738          788    534
2  1/3/26        14           20    933
3  1/4/26       730          904    885
4  1/5/26       114           71    253

# shape = how much row and how much column

In [ ]:
df.shape # 10 rows and 4 columns

(10, 4)

# dtypes = columns haru ko datatype

In [ ]:
df.dtypes

# head() = top 5 from upper

In [ ]:
df.head()

     Date  New York  Los Angeles  Miami
0  1/1/26       985          122    499
1  1/2/26       738          788    534
2  1/3/26        14           20    933
3  1/4/26       730          904    885
4  1/5/26       114           71    253

# tail() = top 5 from buttom

In [ ]:
df.tail()

      Date  New York  Los Angeles  Miami
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

# info() = dataset ko information haru.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10 non-null     object
 1   New York     10 non-null     int64
 2   Los Angeles  10 non-null     int64
 3   Miami        10 non-null     int64
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

# describe =  Nemeric column  haru ko lagi descriptive state output ma dinxa.

In [ ]:
df.describe()

In [ ]:
df

      Date  New York  Los Angeles  Miami
0   1/1/26       985          122    499
1   1/2/26       738          788    534
2   1/3/26        14           20    933
3   1/4/26       730          904    885
4   1/5/26       114           71    253
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

# df[' ' ] = specific column herna lai

In [ ]:
df['New York']

0    985
1    738
2     14
3    730
4    114
5    936
6    123
7    935
8    846
9     54
Name: New York, dtype: int64

# df [[" " , " "]]  = 2 ota column herna lai

In [ ]:
df [['New York' , 'Miami']]

   New York  Miami
0       985    499
1       738    534
2        14    933
3       730    885
4       114    253
5       936    497
6       123    115
7       935    886
8       846    823
9        54    216

In [ ]:
df

      Date  New York  Los Angeles  Miami
0   1/1/26       985          122    499
1   1/2/26       738          788    534
2   1/3/26        14           20    933
3   1/4/26       730          904    885
4   1/5/26       114           71    253
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

# iloc[] = which position access

In [ ]:
df.iloc[0]  # first row ko value access, o is the index

In [ ]:
df.iloc[-1] # last row ko value access, -1 is the index

Date           1/10/26
New York            54
Los Angeles        285
Miami              216
Name: 9, dtype: object

In [ ]:
df.iloc[0:3] # access from 0 to 3 value. 0 is the index and 3 is the index. Ending samma acccess hudoina. i.e 0 to 2 samma matra access hunxa.

In [ ]:
df.iloc[0,1] # 0 ma vako row and 1 ma vako column.If comma aaunxa vaney i.e 0,1 it means find row and column

np.int64(985)

In [ ]:
df

      Date  New York  Los Angeles  Miami
0   1/1/26       985          122    499
1   1/2/26       738          788    534
2   1/3/26        14           20    933
3   1/4/26       730          904    885
4   1/5/26       114           71    253
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

In [ ]:
df.loc[0]

Date           1/1/26
New York          985
Los Angeles       122
Miami             499
Name: 0, dtype: object

# loc = position access, loc means location. It access from start to end. i.e 0 to 3 samma.

In [ ]:
df.loc[0:3] # ending samma acccess hunxa.i.e 0 to 3 samma.

# sample : Everytime print random sample

In [ ]:
df.sample()

     Date  New York  Los Angeles  Miami
0  1/1/26       985          122    499

In [ ]:
df

      Date  New York  Los Angeles  Miami
0   1/1/26       985          122    499
1   1/2/26       738          788    534
2   1/3/26        14           20    933
3   1/4/26       730          904    885
4   1/5/26       114           71    253
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

In [ ]:
df.loc[0, 'New York']  # 0 row ko New York column

np.int64(985)

In [ ]:
df.loc[0:2, "New York":"Miami"] # 0 deko 2 samma ko row and New York and Miami ko column.

   New York  Los Angeles  Miami
0       985          122    499
1       738          788    534
2        14           20    933

# filter

In [ ]:
df

      Date  New York  Los Angeles  Miami
0   1/1/26       985          122    499
1   1/2/26       738          788    534
2   1/3/26        14           20    933
3   1/4/26       730          904    885
4   1/5/26       114           71    253
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

In [ ]:
df[df['New York'] > 800] # New York column ko 800 vanda greater value only give.

# & ()
- AND

In [ ]:
df [(df["New York"] > 800) & (df["Miami"] > 500) ]  # New York column ko 800 vanda greater AND Miami column ko 500 vanda greater value give.

     Date  New York  Los Angeles  Miami
7  1/8/26       935          492    886
8  1/9/26       846          954    823

#  |
- OR
- OR means athwa bujhney, Yo value deu navaye yo value deu.

In [ ]:
df[(df["New York"] > 800) | (df["Miami"] > 500)] # # New York column ko 800 vanda greater OR Miami column ko 500 vanda greater value hunnu paryo.

     Date  New York  Los Angeles  Miami
0  1/1/26       985          122    499
1  1/2/26       738          788    534
2  1/3/26        14           20    933
3  1/4/26       730          904    885
5  1/6/26       936          502    497
7  1/8/26       935          492    886
8  1/9/26       846          954    823

# head() = It gives only Top 5 value from up.

In [ ]:
df1 = pd.read_csv('pokemon.csv')
df1.head()

         Name           Type
0   Bulbasaur  Grass, Poison
1     Ivysaur  Grass, Poison
2    Venusaur  Grass, Poison
3  Charmander           Fire
4  Charmeleon           Fire

# isin()

In [ ]:
df1[df1['Name'].isin(["Bulbasaur", "Ivysaur", "Pikachu"])]

In [ ]:
df = pd.DataFrame({
    'name' : ['Ramesh', 'Rajesh', 'Rabin'],  # name is column, Ramesh,Rajesh,Rabin is value of the column
    'age'  : [25,30,40],
    'salary' : [30000, 400000,70000]
})

print(df)

In [ ]:
df[df['name'].isin(["Rabin", "Rajesh"])]

     name  age  salary
1  Rajesh   30  400000
2   Rabin   40   70000

In [ ]:
df[df['salary'].isin(["Rajesh"])]

Empty DataFrame
Columns: [name, age, salary]
Index: []

In [ ]:
df[df['age'].isin(['Rajesh','Rabin'])]

Empty DataFrame
Columns: [name, age, salary]
Index: []

In [ ]:
df[df['salary'] > 40000]

     name  age  salary
1  Rajesh   30  400000
2   Rabin   40   70000

In [ ]:
df[(df["salary"] > 4000) & (df["age"] > 20) ]

     name  age  salary
0  Ramesh   25   30000
1  Rajesh   30  400000
2   Rabin   40   70000

In [ ]:
df

     name  age  salary
0  Ramesh   25   30000
1  Rajesh   30  400000
2   Rabin   40   70000

# Added new column
- df['new column name'] = df['old column'] +,-,*,/
   - df.head()

In [ ]:
df['bonus'] = df['salary'] * 0.1       # bonus vaney column add garey and salary sitaw multiplication 0.1 garey.
df.head()

# modify old column

In [ ]:
df

In [ ]:
df['age'] = df['age'] +1  # age ma 1 value add garda old ma 29 new ma 30
df.head()

     name  age  salary    bonus
0  Ramesh   26   30000   3000.0
1  Rajesh   31  400000  40000.0
2   Rabin   41   70000   7000.0

In [ ]:
df['senior'] = df['age'] > 30 # Adding senior column if age greater than 30 then True
df.head()

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

# isnull().sum() : It show how much missing value left
- kati ota missing value khali chha.

In [ ]:
df.isnull().sum()    # here kunai column ma pani missing value xoina, 0 means no missing value.

name      0
age       0
salary    0
bonus     0
senior    0
dtype: int64

# dropna()
- if missing value chha vanney.

In [ ]:
df.dropna()

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

# dropna(subset = [' ' ] )
- if kunai column ma missing value chha vanney tyo chai hateraw jaanchha.

In [ ]:
df.dropna(subset=['age'])   # ailey kunai missing value aako xoina ,if chha vanney matra aaunxa.

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

# fillna(0) = missing value ko thau ma 0 lageyraw fill gardinxa.

In [ ]:
df.fillna(0) # missing value xoina so 0 katai fill vayena

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

# STATISTICS

# df['column name'].fillna(df['column name'].mean())
-  specific column ma pani missing value fill garney tarika.

In [ ]:
df['age'].fillna(df['age'].mean()) # yeha missing value xoina So jey chha original tyestai aayo.

0    26
1    31
2    41
Name: age, dtype: int64

In [ ]:
df

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

# Mean = finding average
- df[' column name' ] .mean()

In [ ]:
df['salary'].mean()

np.float64(166666.66666666666)

In [ ]:
df['age'].mean()

np.float64(32.666666666666664)

# Median
- df[' column name' ].median()

In [ ]:
df['salary'].median()

70000.0

In [ ]:
df['age'].median()

31.0

# standard deviation
- df['column name '].std()

In [ ]:
df['salary'].std()

203059.92547357376

# min() = minimum value
- df['column name'].min()

In [ ]:
df['salary'].min()

30000

# max() = maximum value
- df['column'].max()

In [ ]:
df['salary'].max()

400000

# value_counts() = It counts the value how many times repeat.
- kati ota value and kati choti repeat vachha counts garchha.
- df['column name'].value_counts()

In [ ]:
df['salary'].value_counts() # salary ko value kati choti repeat vaako chha.

salary
30000     1
400000    1
70000     1
Name: count, dtype: int64

In [ ]:
df.sort_values('salary')

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
2   Rabin   41   70000   7000.0    True
1  Rajesh   31  400000  40000.0    True

# sort_values = ascending order ma value lai sort gardinxa.
- df.sort_values('column name')

In [ ]:
df  # origina data

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

In [ ]:
df.sort_values('salary')

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
2   Rabin   41   70000   7000.0    True
1  Rajesh   31  400000  40000.0    True

# To make descending order

In [ ]:
df.sort_values('salary', ascending=False)

     name  age  salary    bonus  senior
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True
0  Ramesh   26   30000   3000.0   False

In [ ]:
df

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

In [ ]:
df.sort_values(['senior', 'age'])

     name  age  salary    bonus  senior
0  Ramesh   26   30000   3000.0   False
1  Rajesh   31  400000  40000.0    True
2   Rabin   41   70000   7000.0    True

# rename
- df.rename(columns = {'original column name' : 'new column name' }

In [ ]:
df.rename(columns = {'name':'Full Name', 'age':'years'}, inplace = True)
df.head()

  Full Name  years  salary    bonus  senior
0    Ramesh     26   30000   3000.0   False
1    Rajesh     31  400000  40000.0    True
2     Rabin     41   70000   7000.0    True

# drop = To delete the column
- df.drop(columns = ['columm name'])

In [ ]:
df.drop(columns = ['senior'])

  Full Name  years  salary    bonus
0    Ramesh     26   30000   3000.0
1    Rajesh     31  400000  40000.0
2     Rabin     41   70000   7000.0

In [ ]:
df.head()

  Full Name  years  salary    bonus  senior
0    Ramesh     26   30000   3000.0   False
1    Rajesh     31  400000  40000.0    True
2     Rabin     41   70000   7000.0    True

# To drop the row

In [ ]:
df.drop(index=[0,1])

KeyError: '[0, 1] not found in axis'

In [ ]:
df

  Full Name  years  salary   bonus  senior
2     Rabin     41   70000  7000.0    True

In [ ]:
df.head()

  Full Name  years  salary   bonus  senior
2     Rabin     41   70000  7000.0    True

# To save the file as new

In [ ]:
df.to_csv("Output.csv", index = False)  # file ma yo name save hunchha.

In [ ]:
df.to_excel("Output.xlsx", index=False)

In [ ]:
df = pd.read_csv('employees.csv')
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

# isnull() = It check kati ota mah khaali xa value.
- counting for each column how many null values there produce a new dataframe which display the sum of isnull

In [ ]:
df.isnull().sum()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [ ]:
df.dropna(subset = ['First Name'], inplace = True) # First Name ko missing value haru lai hataidinxa.

In [ ]:
df.isnull().sum()

First Name             0
Gender               138
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management      0
Team                  34
dtype: int64

In [ ]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

# high earners

In [ ]:
high_earners = df[df['Salary'] > 100000]
high_earners

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
990,Robin,Female,7/24/1987,1:35 PM,100765,10.982,True,Client Services
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

# groupby()
- high_earners.groupby(" column ko department name or team name ')['Column name kun ko'].mean()

In [ ]:
# Find the average salary of the team.
high_earners.groupby("Team")['Salary'].mean()

Team
Business Development    122922.022222
Client Services         120210.179487
Distribution            123275.851852
Engineering             124238.317073
Finance                 129043.974359
Human Resources         122308.714286
Legal                   124497.323529
Marketing               126258.432432
Product                 120951.142857
Sales                   124939.558824
Name: Salary, dtype: float64

In [ ]:
# Make it in descending order
high_earners.groupby("Team")['Salary'].mean().sort_values(ascending=False)

Team
Finance                 129043.974359
Marketing               126258.432432
Sales                   124939.558824
Legal                   124497.323529
Engineering             124238.317073
Distribution            123275.851852
Business Development    122922.022222
Human Resources         122308.714286
Product                 120951.142857
Client Services         120210.179487
Name: Salary, dtype: float64